services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container_inventory
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27027:27017"
    volumes:
      - ./mongodb_data:/data/db
